import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";

type Saldo = { id_item: string; nome_item: string; categoria: string | null; codigo_unidade: string; quantidade_saldo: number | string | null; estoque_minimo: number | string | null; status_estoque: string };
type Brassagem = { id: string; numero_brassagem: string; status: string; etapa_atual: string; volume_previsto_litros: number | string; volume_final_litros: number | string | null; iniciada_em: string | null; finalizada_em: string | null };
type Custo = { id_brassagem: string; numero_brassagem: string; status: string; volume_previsto_litros: number | string; volume_final_litros: number | string | null; perda_litros: number | string | null; percentual_perda: number | string | null; custo_total: number | string | null; custo_por_litro: number | string | null };
type Movimento = { id: string; tipo_movimentacao: string; quantidade: number | string; ocorrido_em: string; codigo_item: string | null; observacoes: string | null; id_item: string };
type Item = { id: string; nome: string; codigo_unidade: string };

function numero(value: number | string | null | undefined) { const parsed = Number(value ?? 0); return Number.isFinite(parsed) ? parsed : 0; }
function decimal(value: number | string | null | undefined, digits = 1) { return numero(value).toLocaleString("pt-BR", { minimumFractionDigits: digits, maximumFractionDigits: digits }); }
function moeda(value: number | string | null | undefined) { return numero(value).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
function rotulo(value: string) { const labels: Record<string, string> = { compra: "Entrada", entrada_manual: "Entrada", saida_manual: "Saída", ajuste_entrada: "Entrada", ajuste_saida: "Saída", consumo_brassagem: "Saída", perda: "Perda", em_andamento: "Em andamento", finalizada: "Finalizada", rascunho: "Rascunho", planejamento: "Planejamento", mostura: "Mostura", fervura: "Fervura", fermentacao: "Fermentação", envase: "Envase", vazio: "Crítico", abaixo_minimo: "Abaixo do mínimo", ok: "OK" }; return labels[value] ?? value.replaceAll("_", " "); }
function dataCurta(value: string | null) { return value ? new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "2-digit" }).format(new Date(value)) : "—"; }
function diasAberta(value: string | null) { return value ? Math.floor((Date.now() - new Date(value).getTime()) / 86400000) : 0; }

export default async function Home() {
  const supabase = await createClient();
  const { data: claims } = await supabase.auth.getClaims();
  if (!claims?.claims) redirect("/login");
  const email = typeof claims.claims.email === "string" ? claims.claims.email : "";
  const [{ data: saldos, error: erroSaldos }, { data: brassagens, error: erroBrassagens }, { data: custos }, { data: movimentos }, { data: itens }] = await Promise.all([
    supabase.from("vw_saldos_estoque").select("id_item,nome_item,categoria,codigo_unidade,quantidade_saldo,estoque_minimo,status_estoque").order("status_estoque").order("nome_item"),
    supabase.from("brassagens").select("id,numero_brassagem,status,etapa_atual,volume_previsto_litros,volume_final_litros,iniciada_em,finalizada_em").order("iniciada_em", { ascending: false }).limit(60),
    supabase.from("vw_custos_brassagem").select("id_brassagem,numero_brassagem,status,volume_previsto_litros,volume_final_litros,perda_litros,percentual_perda,custo_total,custo_por_litro").order("numero_brassagem", { ascending: false }).limit(60),
    supabase.from("movimentacoes_estoque").select("id,tipo_movimentacao,quantidade,ocorrido_em,codigo_item,observacoes,id_item").order("ocorrido_em", { ascending: false }).limit(8),
    supabase.from("itens").select("id,nome,codigo_unidade")
  ]);
  const listaSaldos = (saldos ?? []) as Saldo[];
  const listaBrassagens = (brassagens ?? []) as Brassagem[];
  const listaCustos = (custos ?? []) as Custo[];
  const listaMovimentos = (movimentos ?? []) as Movimento[];
  const mapaItens = new Map(((itens ?? []) as Item[]).map((item) => [item.id, item]));
  const criticos = listaSaldos.filter((saldo) => saldo.status_estoque !== "ok");
  const abertas = listaBrassagens.filter((brassagem) => !["finalizada", "cancelada"].includes(brassagem.status));
  const finalizadas = listaCustos.filter((custo) => custo.status === "finalizada");
  const custosComValor = finalizadas.filter((custo) => custo.custo_por_litro !== null);
  const custoMedio = custosComValor.length ? custosComValor.reduce((total, custo) => total + numero(custo.custo_por_litro), 0) / custosComValor.length : null;
  const perdaMedia = finalizadas.length ? finalizadas.reduce((total, custo) => total + numero(custo.percentual_perda) * 100, 0) / finalizadas.length : null;
  const producaoTotal = finalizadas.reduce((total, custo) => total + numero(custo.volume_final_litros), 0);
  const meses = Array.from({ length: 6 }, (_, index) => { const date = new Date(); date.setMonth(date.getMonth() - (5 - index), 1); return { key: `${date.getFullYear()}-${date.getMonth()}`, label: new Intl.DateTimeFormat("pt-BR", { month: "short" }).format(date).replace(".", ""), volume: 0, custo: null as number | null }; });
  for (const custo of finalizadas) { const brassagem = listaBrassagens.find((item) => item.id === custo.id_brassagem); const date = brassagem?.finalizada_em ? new Date(brassagem.finalizada_em) : null; const month = meses.find((item) => date && item.key === `${date.getFullYear()}-${date.getMonth()}`); if (month) { month.volume += numero(custo.volume_final_litros); month.custo = custo.custo_por_litro === null ? month.custo : (month.custo === null ? numero(custo.custo_por_litro) : (month.custo + numero(custo.custo_por_litro)) / 2); } }
  const maiorVolume = Math.max(...meses.map((mes) => mes.volume), 1);
  const maiorCusto = Math.max(...meses.map((mes) => mes.custo ?? 0), custoMedio ?? 1);
  const erros = !saldos && !brassagens ? [erroSaldos?.message, erroBrassagens?.message].filter(Boolean) : [];

  return <AppShell active="painel" userEmail={email} contextLabel="Painel" contextCurrent="Visão geral"><main className="page-shell dashboard-page"><section className="page-content">
    <div className="dashboard-welcome"><div><p className="eyebrow">Olá, {email.split("@")[0] || "cervejeiro"}!</p><p>Aqui está o panorama da sua cervejaria hoje.</p></div><div className="dashboard-date">▣ &nbsp; {new Intl.DateTimeFormat("pt-BR", { dateStyle: "full" }).format(new Date())}</div></div>
    <div className="dashboard-heading"><div><h1>Painel</h1><p>Visão geral da operação da sua cervejaria</p></div><label>Período<select defaultValue="6"><option value="6">Últimos 6 meses</option><option value="12">Último ano</option></select></label></div>
    {erros.length ? <div className="alert-card"><strong>Não foi possível carregar todos os indicadores.</strong><p>{erros.join(" ")}</p></div> : null}
    <section className="dashboard-metrics"><Link href="/estoque?status=critico" className="dashboard-metric"><span className="metric-icon red">▣</span><div><small>Estoque crítico</small><strong>{criticos.length}</strong><em>Ver no estoque →</em></div></Link><div className="dashboard-metric"><span className="metric-icon green">$</span><div><small>Custo médio por litro</small><strong>{custoMedio === null ? "—" : moeda(custoMedio)}</strong><em>{custosComValor.length ? `${custosComValor.length} brassagens calculadas` : "Sem custo real ainda"}</em></div></div><Link href="/brassagens" className="dashboard-metric"><span className="metric-icon green">♙</span><div><small>Brassagens abertas</small><strong>{abertas.length}</strong><em>Acompanhar →</em></div></Link><div className="dashboard-metric"><span className="metric-icon amber">▲</span><div><small>Perdas médias</small><strong>{perdaMedia === null ? "—" : `${decimal(perdaMedia, 1)}%`}</strong><em>{finalizadas.length ? "nas brassagens finalizadas" : "Sem histórico ainda"}</em></div></div></section>
    <div className="dashboard-grid"><section className="panel-card dashboard-chart-card"><div className="section-header"><div><h2>Produção mensal</h2><p>Volume produzido (litros)</p></div><span className="dashboard-filter">Litros⌄</span></div><div className="dashboard-bars">{meses.map((mes) => <div className="dashboard-bar-column" key={mes.key}><strong>{mes.volume ? decimal(mes.volume, 0) : ""}</strong><div className="dashboard-bar-track"><i style={{ height: `${Math.max(4, (mes.volume / maiorVolume) * 100)}%` }} /></div><span>{mes.label}</span></div>)}</div></section><section className="panel-card dashboard-chart-card"><div className="section-header"><div><h2>Evolução do custo por litro</h2><p>Custo médio de produção (R$)</p></div></div><div className="dashboard-cost-chart">{meses.map((mes) => <div className="dashboard-cost-column" key={mes.key}><strong>{mes.custo === null ? "—" : decimal(mes.custo, 2)}</strong><div className="dashboard-cost-track"><i style={{ bottom: `${Math.max(3, ((mes.custo ?? 0) / maiorCusto) * 100)}%` }} /></div><span>{mes.label}</span></div>)}</div></section><section className="panel-card dashboard-alert-card"><div className="section-header"><h2>Alertas</h2><Link href="/estoque">Ver todos →</Link></div>{criticos.slice(0, 4).map((saldo) => <Link className="dashboard-alert" href="/estoque" key={`${saldo.id_item}-${saldo.codigo_unidade}`}><span className="alert-icon">!</span><div><strong>{saldo.nome_item}</strong><small>{rotulo(saldo.status_estoque)} ({decimal(saldo.quantidade_saldo, 2)} {saldo.codigo_unidade})</small></div></Link>)}{abertas.filter((brassagem) => diasAberta(brassagem.iniciada_em) > 5).slice(0, 2).map((brassagem) => <Link className="dashboard-alert warning" href={`/brassagens/${brassagem.id}`} key={brassagem.id}><span className="alert-icon">▲</span><div><strong>{brassagem.numero_brassagem}</strong><small>{rotulo(brassagem.etapa_atual)} há {diasAberta(brassagem.iniciada_em)} dias</small></div></Link>)}{!criticos.length && !abertas.length ? <p className="dashboard-empty">Nenhum alerta no momento.</p> : null}</section></div>
    <div className="dashboard-lower-grid"><section className="panel-card"><div className="section-header"><h2>Últimas movimentações</h2><Link href="/estoque">Ver todas →</Link></div><div className="dashboard-movement-table"><div className="dashboard-movement-head"><span>Data</span><span>Tipo</span><span>Item</span><span>Descrição</span><span>Quantidade</span></div>{listaMovimentos.map((movimento) => { const item = mapaItens.get(movimento.id_item); const entrada = ["compra", "entrada_manual", "ajuste_entrada"].includes(movimento.tipo_movimentacao); return <div className="dashboard-movement-row" key={movimento.id}><span>{dataCurta(movimento.ocorrido_em)}</span><b className={entrada ? "in" : "out"}>{entrada ? "Entrada" : "Saída"}</b><strong>{item?.nome ?? movimento.codigo_item ?? "Item"}</strong><span>{movimento.observacoes ?? rotulo(movimento.tipo_movimentacao)}</span><em className={entrada ? "in" : "out"}>{entrada ? "+" : "−"}{decimal(movimento.quantidade, 2)} {item?.codigo_unidade ?? ""}</em></div>; })}{!listaMovimentos.length ? <p className="dashboard-empty">Nenhuma movimentação registrada.</p> : null}</div></section><section className="panel-card dashboard-actions-card"><div className="section-header"><h2>Próximas ações</h2><Link href="/brassagens">Ver todas →</Link></div>{abertas.slice(0, 4).map((brassagem) => <Link className="dashboard-next-action" href={`/brassagens/${brassagem.id}`} key={brassagem.id}><span>□</span><span>Verificar {rotulo(brassagem.etapa_atual).toLowerCase()} da {brassagem.numero_brassagem}</span><time>{dataCurta(brassagem.iniciada_em)}</time></Link>)}<Link className="dashboard-next-action" href="/estoque"><span>□</span><span>Revisar níveis de estoque</span><time>Hoje</time></Link><Link className="dashboard-next-action" href="/relatorios"><span>□</span><span>Revisar custos e perdas</span><time>Relatórios</time></Link>{!abertas.length ? <p className="dashboard-empty">Abra uma brassagem para acompanhar ações.</p> : null}</section></div>
    <p className="dashboard-footnote">Produção total finalizada: <strong>{decimal(producaoTotal, 1)} L</strong> · {finalizadas.length} brassagem(ns) finalizada(s) no histórico.</p>
  </section></main></AppShell>;
}
