"use client";

import { useState } from "react";

type Capturado = { nome: string; grupo: string; fornecedor: string; quantidade: number; unidade: string; custo: number | null };

function numero(valor: unknown) { const n = Number(String(valor ?? "").replace(/\./g, "").replace(",", ".")); return Number.isFinite(n) ? n : 0; }
function grupo(valor: string) { const texto = valor.toLocaleLowerCase(); if (/lup|hop/.test(texto)) return "Lúpulo"; if (/leved|yeast/.test(texto)) return "Levedura"; if (/malte|malt|ferment/.test(texto)) return "Malte"; return "Diversos"; }
function parseLinha(linha: string, cabecalho?: string[]) { const separador = linha.includes("\t") ? "\t" : linha.includes(";") ? ";" : ","; const partes = linha.split(separador).map((parte) => parte.trim().replace(/^"|"$/g, "")); if (cabecalho) { const valor = (nomes: string[]) => { const indice = cabecalho.findIndex((item) => nomes.includes(item)); return indice >= 0 ? partes[indice] ?? "" : ""; }; return { nome: valor(["nome", "name", "item", "ingredient"]) || partes[0] || "", grupo: grupo(valor(["grupo", "categoria", "type", "tipo"])), fornecedor: valor(["fornecedor", "supplier", "brand"]), quantidade: numero(valor(["quantidade", "quantity", "inventory", "estoque", "amount"])), unidade: valor(["unidade", "unit", "units"]) || "g", custo: numero(valor(["custo", "cost", "price"])) || null }; } return { nome: partes[0] || "", grupo: grupo(partes[1] || ""), fornecedor: partes[2] || "", quantidade: numero(partes[3]), unidade: partes[4] || "g", custo: numero(partes[5]) || null }; }
function analisar(texto: string): Capturado[] { const limpo = texto.trim(); if (!limpo) return []; try { const json = JSON.parse(limpo) as unknown; const lista = Array.isArray(json) ? json : json && typeof json === "object" && Array.isArray((json as { items?: unknown }).items) ? (json as { items: unknown[] }).items : null; if (lista) return lista.flatMap((item) => { if (!item || typeof item !== "object") return []; const registro = item as Record<string, unknown>; return [{ nome: String(registro.name ?? registro.nome ?? "").trim(), grupo: grupo(String(registro.type ?? registro.tipo ?? registro.category ?? registro.categoria ?? "")), fornecedor: String(registro.supplier ?? registro.fornecedor ?? registro.brand ?? "").trim(), quantidade: numero(registro.inventory ?? registro.quantidade ?? registro.quantity), unidade: String(registro.unit ?? registro.unidade ?? "g"), custo: numero(registro.cost ?? registro.custo ?? registro.price) || null }]; }).filter((item) => item.nome); } catch { /* texto tabular */ } const linhas = limpo.split(/\r?\n/).map((linha) => linha.trim()).filter(Boolean); if (!linhas.length) return []; const primeira = linhas[0].toLocaleLowerCase(); const temCabecalho = /nome|name|ingredient|ingrediente/.test(primeira); const cabecalho = temCabecalho ? (linhas.shift() ?? "").split(linhas[0]?.includes("\t") ? "\t" : linhas[0]?.includes(";") ? ";" : ",").map((item) => item.trim().toLocaleLowerCase()) : undefined; return linhas.map((linha) => parseLinha(linha, cabecalho)).filter((item) => item.nome); }

export function BrewfatherCapture() {
  const [texto, setTexto] = useState(""); const [itens, setItens] = useState<Capturado[]>([]); const [selecionados, setSelecionados] = useState<number[]>([]); const [incluirSaldo, setIncluirSaldo] = useState(true); const [erro, setErro] = useState(""); const [mensagem, setMensagem] = useState(""); const [importando, setImportando] = useState(false);
  function analisarTexto() { const lista = analisar(texto); setItens(lista); setSelecionados(lista.map((_, indice) => indice)); setErro(lista.length ? "" : "Não encontrei linhas com nome de ingrediente."); setMensagem(""); }
  async function importar() { setImportando(true); setErro(""); setMensagem(""); try { const resposta = await fetch("/api/integracoes/brewfather/captura", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ itens: selecionados.map((indice) => itens[indice]), incluirSaldo }) }); const corpo = await resposta.json() as { imported?: number; skipped?: number; error?: string }; if (!resposta.ok) throw new Error(corpo.error ?? "Não foi possível importar a captura."); setMensagem(`${corpo.imported ?? 0} item(ns) importado(s) e ${corpo.skipped ?? 0} ignorado(s) por duplicidade.`); } catch (error) { setErro(error instanceof Error ? error.message : "Não foi possível importar a captura."); } finally { setImportando(false); } }
  return <div className="brewfather-capture"><div className="brewfather-capture-help"><p className="eyebrow">Sem API paga</p><h2>Captura assistida da tela</h2><p className="section-help">No Brewfather, selecione e copie as linhas da lista de insumos. Cole o conteúdo abaixo. Aceitamos texto separado por tabulação, CSV, ou JSON copiado da tela.</p></div><textarea className="brewfather-capture-input" value={texto} onChange={(event) => setTexto(event.target.value)} placeholder="Nome | Grupo | Fornecedor | Quantidade | Unidade\nMalte Pilsen | Malte | Weyermann | 5000 | g" rows={8} /><div className="brewfather-capture-actions"><button className="button secondary" type="button" onClick={analisarTexto}>Analisar conteúdo</button>{itens.length ? <label className="brewfather-check"><input type="checkbox" checked={incluirSaldo} onChange={(event) => setIncluirSaldo(event.target.checked)} /> Importar saldo informado</label> : null}{itens.length ? <button className="button primary" type="button" disabled={!selecionados.length || importando} onClick={importar}>{importando ? "Importando…" : `Importar selecionados (${selecionados.length})`}</button> : null}</div>{erro ? <p className="form-message error">{erro}</p> : null}{mensagem ? <p className="form-message success">{mensagem}</p> : null}{itens.length ? <div className="table-wrap"><table className="brewfather-table"><thead><tr><th></th><th>Insumo</th><th>Grupo</th><th>Fornecedor</th><th>Quantidade</th></tr></thead><tbody>{itens.map((item, indice) => <tr key={`${item.nome}-${indice}`}><td><input type="checkbox" checked={selecionados.includes(indice)} onChange={() => setSelecionados((atual) => atual.includes(indice) ? atual.filter((valor) => valor !== indice) : [...atual, indice])} /></td><td><strong>{item.nome}</strong></td><td>{item.grupo}</td><td>{item.fornecedor || "—"}</td><td>{item.quantidade.toLocaleString("pt-BR")} {item.unidade}</td></tr>)}</tbody></table></div> : null}</div>;
}
