import Link from "next/link";
import { editarLote, registrarEntrada, registrarMovimentacao } from "@/app/estoque/actions";

export type StockSaldo = {
  id_item: string; nome_item: string; tipo_item: string; categoria: string; codigo_unidade: string;
  id_lote: string | null; codigo_lote: string | null; validade: string | null;
  custo_unitario: number | string | null; quantidade_saldo: number | string | null;
  estoque_minimo: number | string; status_estoque: string;
};
export type StockItem = { id: string; nome: string; codigo_item: string; codigo_grupo: string; codigo_unidade: string; imagem_url: string | null };
export type StockFornecedor = { id: string; nome: string };
export type StockUnidade = { codigo: string; nome: string; tipo: string; unidade_base: string; fator_para_base: number | string };
export type StockLote = { id: string; id_item: string; codigo_item: string; codigo_grupo: string; id_fornecedor: string | null; codigo_lote: string; custo_unitario: number | string; validade: string | null };
export type StockMovimento = { id: string; id_item: string; id_lote: string | null; codigo_item: string; codigo_grupo: string; tipo_movimentacao: string; quantidade: number | string; custo_unitario: number | string | null; ocorrido_em: string; observacoes: string | null };

type StockParams = { q?: string; tipo?: string; categoria?: string; status?: string; validade?: string; fornecedor?: string; lote?: string; error?: string; message?: string };

const tipoLabel: Record<string, string> = { compra: "Compra", entrada_manual: "Entrada manual", saida_manual: "Saída manual", ajuste_entrada: "Ajuste de entrada", ajuste_saida: "Ajuste de saída", perda: "Perda" };
const tiposEntrada = new Set(["compra", "entrada_manual", "ajuste_entrada"]);
function numero(value: number | string | null | undefined) { const parsed = Number(value ?? 0); return Number.isFinite(parsed) ? parsed : 0; }
function decimal(value: number | string | null | undefined, digits = 2) { return numero(value).toLocaleString("pt-BR", { minimumFractionDigits: digits, maximumFractionDigits: digits }); }
function dataCurta(value: string | null) { return value ? new Intl.DateTimeFormat("pt-BR").format(new Date(value)) : "—"; }
function iconeItem(categoria: string) { const nome = categoria.toLocaleLowerCase(); if (nome.includes("malte")) return "🌾"; if (nome.includes("lúpulo") || nome.includes("lupulo")) return "🍃"; if (nome.includes("levedura")) return "🧫"; if (nome.includes("embalagem")) return "🍾"; return "▣"; }
function validadeStatus(value: string | null) { if (!value) return "sem_validade"; const hoje = new Date(); hoje.setHours(0, 0, 0, 0); const validade = new Date(`${value}T12:00:00`); const limite = new Date(hoje); limite.setDate(limite.getDate() + 45); if (validade < hoje) return "vencido"; if (validade <= limite) return "vencendo"; return "valido"; }

function FormularioEdicaoLote({ saldo, lote }: { saldo: StockSaldo; lote: StockLote }) {
  return <form className="details-form" action={editarLote}><input type="hidden" name="id_lote" value={lote.id} /><label className="form-field"><span>Código do lote *</span><input name="codigo_lote" defaultValue={lote.codigo_lote} required maxLength={80} /></label><label className="form-field"><span>Validade</span><input name="validade" type="date" defaultValue={lote.validade ?? ""} /></label><label className="form-field"><span>Saldo desejado ({saldo.codigo_unidade}) *</span><input name="quantidade_desejada" type="number" min="0" step="0.001" defaultValue={numero(saldo.quantidade_saldo)} required /></label><label className="form-field"><span>Valor por unidade ({saldo.codigo_unidade}) *</span><input name="custo_unitario" type="number" min="0" step="0.0001" defaultValue={numero(saldo.custo_unitario)} required /><small>Ex.: R$ por kg, g, litro ou unidade.</small></label><button className="button primary" type="submit">Salvar lote</button></form>;
}

export function StockInventory({ email, params, saldos, itens, fornecedores, lotes, movimentos, unidades }: { email?: string; params: StockParams; saldos: StockSaldo[]; itens: StockItem[]; fornecedores: StockFornecedor[]; lotes: StockLote[]; movimentos: StockMovimento[]; unidades: StockUnidade[] }) {
  const itemPorId = new Map(itens.map((item) => [item.id, item]));
  const lotePorId = new Map(lotes.map((lote) => [lote.id, lote]));
  const fornecedorPorId = new Map(fornecedores.map((fornecedor) => [fornecedor.id, fornecedor.nome]));
  const tipoSelecionado = ["ingrediente", "embalagem", "produto_acabado"].includes(params.tipo ?? "") ? params.tipo! : "ingrediente";
  const busca = params.q?.trim().toLocaleLowerCase();
  const saldosDoTipo = saldos.filter((saldo) => saldo.tipo_item === tipoSelecionado);
  const categorias = [...new Set(saldosDoTipo.map((saldo) => saldo.categoria).filter(Boolean))].sort((a, b) => a.localeCompare(b));
  const saldosFiltrados = saldosDoTipo.filter((saldo) => {
    const lote = saldo.id_lote ? lotePorId.get(saldo.id_lote) : null;
    const fornecedor = lote?.id_fornecedor ? fornecedorPorId.get(lote.id_fornecedor) ?? "" : "";
    return (!busca || `${saldo.nome_item} ${saldo.codigo_lote ?? ""} ${fornecedor}`.toLocaleLowerCase().includes(busca))
      && (!params.categoria || saldo.categoria === params.categoria)
      && (!params.status || saldo.status_estoque === params.status)
      && (!params.validade || validadeStatus(saldo.validade) === params.validade)
      && (!params.fornecedor || lote?.id_fornecedor === params.fornecedor);
  });
  const loteSelecionado = params.lote ? lotePorId.get(params.lote) : null;
  const saldoSelecionado = saldosFiltrados.find((saldo) => saldo.id_lote === loteSelecionado?.id) ?? saldosFiltrados.find((saldo) => saldo.id_lote) ?? null;
  const loteDetalhe = saldoSelecionado?.id_lote ? lotePorId.get(saldoSelecionado.id_lote) ?? null : null;
  const itemDetalhe = saldoSelecionado ? itemPorId.get(saldoSelecionado.id_item) : null;
  const movimentosDetalhe = saldoSelecionado?.id_lote ? movimentos.filter((movimento) => movimento.id_lote === saldoSelecionado.id_lote).slice(0, 5) : [];
  const valorEstoque = saldosDoTipo.reduce((total, saldo) => total + numero(saldo.quantidade_saldo) * numero(saldo.custo_unitario), 0);
  const queryBase = `tipo=${tipoSelecionado}${params.q ? `&q=${encodeURIComponent(params.q)}` : ""}${params.categoria ? `&categoria=${encodeURIComponent(params.categoria)}` : ""}${params.status ? `&status=${params.status}` : ""}${params.validade ? `&validade=${params.validade}` : ""}${params.fornecedor ? `&fornecedor=${params.fornecedor}` : ""}`;

  return <main className="page-shell stock-page"><section className="page-content">
    <div className="stock-header"><div><h1>Estoque</h1><p className="intro">Controle de insumos, embalagens e produtos acabados</p></div><div className="stock-header-total"><span>Valor estimado</span><strong>R$ {decimal(valorEstoque)}</strong></div></div>
    {params.error ? <p className="form-message error">{params.error}</p> : null}{params.message ? <p className="form-message success">{params.message}</p> : null}
    <div className="stock-actions-top"><a className="button primary" href="#nova-entrada">＋ Nova entrada</a><a className="button secondary" href="#nova-movimentacao">↓ Registrar baixa</a><a className="button secondary" href="#nova-movimentacao">✎ Ajuste</a></div>
    <div className="stock-layout">
      <section className="stock-list-panel">
        <nav className="stock-tabs" aria-label="Tipo de estoque"><Link className={tipoSelecionado === "ingrediente" ? "active" : ""} href="/estoque?tipo=ingrediente">Insumos</Link><Link className={tipoSelecionado === "embalagem" ? "active" : ""} href="/estoque?tipo=embalagem">Embalagens</Link><Link className={tipoSelecionado === "produto_acabado" ? "active" : ""} href="/estoque?tipo=produto_acabado">Produtos acabados</Link></nav>
        <form className="stock-filter-bar" method="get"><input type="hidden" name="tipo" value={tipoSelecionado} /><div className="stock-search"><span aria-hidden="true">⌕</span><input name="q" defaultValue={params.q ?? ""} placeholder="Buscar item, lote ou fornecedor..." /></div><div className="stock-filter-grid"><label>Categoria<select name="categoria" defaultValue={params.categoria ?? ""}><option value="">Todas</option>{categorias.map((categoria) => <option value={categoria} key={categoria}>{categoria}</option>)}</select></label><label>Status<select name="status" defaultValue={params.status ?? ""}><option value="">Todos</option><option value="ok">OK</option><option value="abaixo_minimo">Abaixo do mínimo</option><option value="vazio">Crítico</option></select></label><label>Validade<select name="validade" defaultValue={params.validade ?? ""}><option value="">Todas</option><option value="valido">Válida</option><option value="vencendo">Vencendo em 45 dias</option><option value="vencido">Vencida</option><option value="sem_validade">Sem validade</option></select></label><label>Fornecedor<select name="fornecedor" defaultValue={params.fornecedor ?? ""}><option value="">Todos</option>{fornecedores.map((fornecedor) => <option value={fornecedor.id} key={fornecedor.id}>{fornecedor.nome}</option>)}</select></label></div><button className="stock-clear" type="submit">Aplicar filtros</button></form>
        <div className="table-wrap stock-table-wrap"><table className="stock-table"><thead><tr><th>Item</th><th>Categoria</th><th>Lote</th><th>Validade</th><th>Saldo</th><th>Mínimo</th><th>Custo atual</th><th>Status</th><th aria-label="Selecionar" /></tr></thead><tbody>{saldosFiltrados.map((saldo) => { const item = itemPorId.get(saldo.id_item); const lote = saldo.id_lote ? lotePorId.get(saldo.id_lote) : null; const selecionado = saldo.id_lote === saldoSelecionado?.id_lote; const link = `/estoque?${queryBase}${saldo.id_lote ? `&lote=${saldo.id_lote}` : ""}`; return <tr className={selecionado ? "selected" : ""} key={`${saldo.id_item}-${saldo.id_lote ?? "sem-lote"}`}><td><Link className="stock-item-cell" href={link}><span className="stock-item-icon">{item?.imagem_url ? <img src={item.imagem_url} alt="" loading="lazy" /> : iconeItem(saldo.categoria)}</span><span><strong>{saldo.nome_item}</strong><small>{item?.codigo_item ?? "—"} · {item?.codigo_grupo ?? saldo.categoria}</small></span></Link></td><td>{saldo.categoria || "—"}</td><td>{saldo.codigo_lote ?? "Sem lote"}</td><td>{dataCurta(saldo.validade)}</td><td><strong>{decimal(saldo.quantidade_saldo, 3)} {saldo.codigo_unidade}</strong></td><td>{decimal(saldo.estoque_minimo, 3)} {saldo.codigo_unidade}</td><td>R$ {decimal(saldo.custo_unitario, 4)} / {saldo.codigo_unidade}</td><td><span className={`table-pill ${saldo.status_estoque}`}>{saldo.status_estoque === "abaixo_minimo" ? "Abaixo do mínimo" : saldo.status_estoque === "vazio" ? "Crítico" : "OK"}</span></td><td className="stock-row-actions">{lote ? <><Link className="stock-row-arrow" href={link} aria-label={`Ver detalhes de ${saldo.nome_item}`}>›</Link><details className="row-details"><summary>Editar</summary><FormularioEdicaoLote saldo={saldo} lote={lote} /></details></> : <span>—</span>}</td></tr>; })}</tbody></table></div><p className="table-footnote">Mostrando {saldosFiltrados.length} de {saldosDoTipo.length} itens.</p>
      </section>
      <aside className="stock-detail-panel">{saldoSelecionado && loteDetalhe ? <>
        <div className="detail-heading"><span className="detail-item-icon">{itemDetalhe?.imagem_url ? <img src={itemDetalhe.imagem_url} alt="" /> : iconeItem(saldoSelecionado.categoria)}</span><div><h2>{saldoSelecionado.nome_item}</h2><p>{itemDetalhe?.codigo_grupo ?? saldoSelecionado.categoria}</p></div><Link href={`/estoque?${queryBase}`} aria-label="Fechar detalhes">×</Link></div><span className={`detail-status ${saldoSelecionado.status_estoque}`}>{saldoSelecionado.status_estoque === "abaixo_minimo" ? "● Abaixo do mínimo" : saldoSelecionado.status_estoque === "vazio" ? "● Crítico" : "● OK"}</span>
        <div className="detail-tabs"><span className="active">Visão geral</span><span>Movimentações</span><span>Histórico de custo</span></div><dl className="detail-grid"><dt>Lote</dt><dd>{loteDetalhe.codigo_lote}</dd><dt>Categoria</dt><dd>{saldoSelecionado.categoria || "—"}</dd><dt>Saldo atual</dt><dd>{decimal(saldoSelecionado.quantidade_saldo, 3)} {saldoSelecionado.codigo_unidade}</dd><dt>Mínimo</dt><dd>{decimal(saldoSelecionado.estoque_minimo, 3)} {saldoSelecionado.codigo_unidade}</dd><dt>Custo atual</dt><dd>R$ {decimal(saldoSelecionado.custo_unitario, 4)} / {saldoSelecionado.codigo_unidade}</dd><dt>Validade</dt><dd>{dataCurta(saldoSelecionado.validade)}</dd><dt>Fornecedor</dt><dd>{loteDetalhe.id_fornecedor ? fornecedorPorId.get(loteDetalhe.id_fornecedor) ?? "—" : "—"}</dd></dl>
        <div className="detail-section"><div className="detail-section-title"><h3>Movimentações recentes</h3><span>Ver todas</span></div>{movimentosDetalhe.length ? <div className="movement-list">{movimentosDetalhe.map((movimento) => <div className="movement-row" key={movimento.id}><span className={`movement-icon ${tiposEntrada.has(movimento.tipo_movimentacao) ? "in" : "out"}`}>{tiposEntrada.has(movimento.tipo_movimentacao) ? "↑" : "↓"}</span><span><strong>{tipoLabel[movimento.tipo_movimentacao] ?? movimento.tipo_movimentacao}</strong><small>{dataCurta(movimento.ocorrido_em)}</small></span><b className={tiposEntrada.has(movimento.tipo_movimentacao) ? "positive" : "negative"}>{tiposEntrada.has(movimento.tipo_movimentacao) ? "+" : "−"}{decimal(movimento.quantidade, 3)} {saldoSelecionado.codigo_unidade}</b></div>)}</div> : <p className="detail-empty">Nenhuma movimentação registrada.</p>}</div>
        <div className="detail-actions"><a className="button primary" href="#nova-entrada">↑ Entrada</a><a className="button secondary" href="#nova-movimentacao">↓ Baixa</a><details className="detail-edit"><summary className="button secondary">✎ Editar</summary><FormularioEdicaoLote saldo={saldoSelecionado} lote={loteDetalhe} /></details></div>
      </> : <div className="detail-empty detail-empty-large"><strong>Selecione um lote</strong><span>Escolha uma linha para visualizar os detalhes.</span></div>}</aside>
    </div>
    <details className="stock-action-panel" id="nova-entrada"><summary>＋ Nova entrada</summary><div className="stock-action-content"><div className="section-header"><div><p className="eyebrow">Entrada de compra</p><h2>Novo lote</h2><p className="section-help">Informe a quantidade na unidade da compra; o saldo será convertido para a unidade-base do item.</p></div><span className="status-pill configured">Conversão automática</span></div><form className="form-grid" action={registrarEntrada}><label className="form-field"><span>Item *</span><select name="id_item" required defaultValue=""><option value="" disabled>Selecione o item</option>{itens.map((item) => <option value={item.id} key={item.id}>{item.nome} · base: {item.codigo_unidade}</option>)}</select></label><label className="form-field"><span>Unidade da entrada *</span><select name="codigo_unidade_entrada" required defaultValue=""><option value="" disabled>Selecione a unidade</option>{unidades.map((unidade) => <option value={unidade.codigo} key={unidade.codigo}>{unidade.codigo} · {unidade.nome}</option>)}</select></label><label className="form-field"><span>Fornecedor</span><select name="id_fornecedor" defaultValue=""><option value="">Não informado</option>{fornecedores.map((fornecedor) => <option value={fornecedor.id} key={fornecedor.id}>{fornecedor.nome}</option>)}</select></label><label className="form-field"><span>Código do lote *</span><input name="codigo_lote" required placeholder="Ex.: MAL-2609" /></label><label className="form-field"><span>Quantidade *</span><input name="quantidade" type="number" min="0.001" step="0.001" required placeholder="0,000" /></label><label className="form-field"><span>Custo por unidade informada *</span><input name="custo_unitario" type="number" min="0" step="0.0001" required placeholder="R$ 0,00" /></label><label className="form-field"><span>Recebido em *</span><input name="recebido_em" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></label><label className="form-field"><span>Validade</span><input name="validade" type="date" /></label><label className="form-field form-field-wide"><span>Observações</span><textarea name="observacoes" rows={2} placeholder="Nota fiscal, condição de pagamento ou localização" /></label><div className="form-actions form-field-wide"><button className="button primary" type="submit">Salvar entrada</button></div></form></div></details>
    <details className="stock-action-panel" id="nova-movimentacao"><summary>↓ Registrar baixa ou ajuste</summary><div className="stock-action-content"><div className="section-header"><div><p className="eyebrow">Baixa e ajustes</p><h2>Registrar movimentação</h2><p className="section-help">A unidade escolhida também será convertida para a unidade-base do lote.</p></div><span className="status-pill pending">Saídas validam o saldo</span></div><form className="form-grid" action={registrarMovimentacao}><label className="form-field"><span>Lote *</span><select name="id_lote" required defaultValue={saldoSelecionado?.id_lote ?? ""}><option value="" disabled>Selecione o lote</option>{lotes.map((lote) => <option value={lote.id} key={lote.id}>{lote.codigo_lote} · {itemPorId.get(lote.id_item)?.nome ?? "Item"}</option>)}</select></label><label className="form-field"><span>Unidade informada *</span><select name="codigo_unidade_entrada" required defaultValue=""><option value="" disabled>Selecione a unidade</option>{unidades.map((unidade) => <option value={unidade.codigo} key={unidade.codigo}>{unidade.codigo} · {unidade.nome}</option>)}</select></label><label className="form-field"><span>Tipo *</span><select name="tipo_movimentacao" required defaultValue="saida_manual"><option value="saida_manual">Saída manual</option><option value="perda">Perda</option><option value="entrada_manual">Entrada manual</option><option value="ajuste_entrada">Ajuste de entrada</option><option value="ajuste_saida">Ajuste de saída</option></select></label><label className="form-field"><span>Quantidade *</span><input name="quantidade" type="number" min="0.001" step="0.001" required placeholder="0,000" /></label><label className="form-field"><span>Data *</span><input name="ocorrido_em" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></label><label className="form-field"><span>Custo por unidade informada</span><input name="custo_unitario" type="number" min="0" step="0.0001" placeholder="Usa o custo do lote" /></label><label className="form-field form-field-wide"><span>Motivo / observações</span><textarea name="observacoes" rows={2} placeholder="Ex.: quebra, inventário ou uso fora da produção" /></label><div className="form-actions form-field-wide"><button className="button secondary" type="submit">Registrar movimentação</button></div></form></div></details>
  </section></main>;
}
