-- Traduz nomes internos que aparecem no painel do Supabase.
-- Nao altera dados nem regras; apenas renomeia constraints, indices, triggers e policies.

alter table public.usuarios_app rename constraint app_users_pkey to pk_usuarios_app;
alter table public.usuarios_app rename constraint app_users_auth_user_id_key to uq_usuarios_app_id_usuario_auth;
alter table public.usuarios_app rename constraint app_users_email_key to uq_usuarios_app_email;

alter table public.fornecedores rename constraint suppliers_pkey to pk_fornecedores;
alter table public.fornecedores rename constraint suppliers_name_unique to uq_fornecedores_nome;

alter table public.unidades rename constraint units_pkey to pk_unidades;

alter table public.itens rename constraint items_pkey to pk_itens;
alter table public.itens rename constraint items_name_type_unique to uq_itens_nome_tipo;
alter table public.itens rename constraint items_unit_code_fkey to fk_itens_codigo_unidade;
alter table public.itens rename constraint items_minimum_stock_check to chk_itens_estoque_minimo_nao_negativo;
alter table public.itens rename constraint items_reference_cost_check to chk_itens_custo_referencia_nao_negativo;

alter table public.lotes_itens rename constraint item_lots_pkey to pk_lotes_itens;
alter table public.lotes_itens rename constraint item_lots_item_code_unique to uq_lotes_itens_item_codigo_lote;
alter table public.lotes_itens rename constraint item_lots_item_id_fkey to fk_lotes_itens_id_item;
alter table public.lotes_itens rename constraint item_lots_supplier_id_fkey to fk_lotes_itens_id_fornecedor;
alter table public.lotes_itens rename constraint item_lots_unit_cost_check to chk_lotes_itens_custo_unitario_nao_negativo;

alter table public.movimentacoes_estoque rename constraint stock_movements_pkey to pk_movimentacoes_estoque;
alter table public.movimentacoes_estoque rename constraint stock_movements_item_id_fkey to fk_movimentacoes_estoque_id_item;
alter table public.movimentacoes_estoque rename constraint stock_movements_lot_id_fkey to fk_movimentacoes_estoque_id_lote;
alter table public.movimentacoes_estoque rename constraint stock_movements_created_by_fkey to fk_movimentacoes_estoque_criado_por;
alter table public.movimentacoes_estoque rename constraint stock_movement_lot_item_required to chk_movimentacoes_estoque_lote_compativel;
alter table public.movimentacoes_estoque rename constraint stock_movements_quantity_check to chk_movimentacoes_estoque_quantidade_positiva;
alter table public.movimentacoes_estoque rename constraint stock_movements_unit_cost_check to chk_movimentacoes_estoque_custo_unitario_nao_negativo;

alter table public.receitas rename constraint recipes_pkey to pk_receitas;
alter table public.receitas rename constraint recipes_name_key to uq_receitas_nome;
alter table public.receitas rename constraint recipes_target_volume_liters_check to chk_receitas_volume_previsto_positivo;

alter table public.versoes_receitas rename constraint recipe_versions_pkey to pk_versoes_receitas;
alter table public.versoes_receitas rename constraint recipe_versions_recipe_id_fkey to fk_versoes_receitas_id_receita;
alter table public.versoes_receitas rename constraint recipe_versions_unique to uq_versoes_receitas_receita_versao;
alter table public.versoes_receitas rename constraint recipe_versions_version_number_check to chk_versoes_receitas_numero_versao_positivo;

alter table public.insumos_receita rename constraint recipe_inputs_pkey to pk_insumos_receita;
alter table public.insumos_receita rename constraint recipe_inputs_recipe_version_id_fkey to fk_insumos_receita_id_versao_receita;
alter table public.insumos_receita rename constraint recipe_inputs_item_id_fkey to fk_insumos_receita_id_item;
alter table public.insumos_receita rename constraint recipe_inputs_unique to uq_insumos_receita_versao_item_etapa_ordem;
alter table public.insumos_receita rename constraint recipe_inputs_planned_quantity_check to chk_insumos_receita_quantidade_prevista_positiva;

alter table public.brassagens rename constraint brew_batches_pkey to pk_brassagens;
alter table public.brassagens rename constraint brew_batches_batch_number_key to uq_brassagens_numero;
alter table public.brassagens rename constraint brew_batches_recipe_version_id_fkey to fk_brassagens_id_versao_receita;
alter table public.brassagens rename constraint brew_batches_created_by_fkey to fk_brassagens_criado_por;
alter table public.brassagens rename constraint brew_batches_planned_volume_liters_check to chk_brassagens_volume_previsto_positivo;
alter table public.brassagens rename constraint brew_batches_final_volume_liters_check to chk_brassagens_volume_final_nao_negativo;
alter table public.brassagens rename constraint finalized_batches_need_final_volume to chk_brassagens_finalizada_exige_volume_final;
alter table public.brassagens rename constraint stock_posted_only_after_finalized to chk_brassagens_baixa_estoque_so_finalizada;

alter table public.consumos_brassagem rename constraint brew_batch_consumptions_pkey to pk_consumos_brassagem;
alter table public.consumos_brassagem rename constraint brew_batch_consumptions_brew_batch_id_fkey to fk_consumos_brassagem_id_brassagem;
alter table public.consumos_brassagem rename constraint brew_batch_consumptions_recipe_input_id_fkey to fk_consumos_brassagem_id_insumo_receita;
alter table public.consumos_brassagem rename constraint brew_batch_consumptions_item_id_fkey to fk_consumos_brassagem_id_item;
alter table public.consumos_brassagem rename constraint brew_batch_consumptions_lot_id_fkey to fk_consumos_brassagem_id_lote;
alter table public.consumos_brassagem rename constraint brew_batch_consumptions_stock_movement_id_fkey to fk_consumos_brassagem_id_movimentacao_estoque;
alter table public.consumos_brassagem rename constraint brew_batch_consumptions_stock_movement_id_key to uq_consumos_brassagem_id_movimentacao_estoque;
alter table public.consumos_brassagem rename constraint brew_batch_consumptions_planned_quantity_check to chk_consumos_brassagem_quantidade_prevista_positiva;
alter table public.consumos_brassagem rename constraint brew_batch_consumptions_actual_quantity_check to chk_consumos_brassagem_quantidade_real_positiva;

alter table public.custos_extras_brassagem rename constraint brew_batch_extra_costs_pkey to pk_custos_extras_brassagem;
alter table public.custos_extras_brassagem rename constraint brew_batch_extra_costs_brew_batch_id_fkey to fk_custos_extras_brassagem_id_brassagem;
alter table public.custos_extras_brassagem rename constraint brew_batch_extra_costs_amount_check to chk_custos_extras_brassagem_valor_nao_negativo;

alter table public.eventos_brassagem rename constraint brew_batch_events_pkey to pk_eventos_brassagem;
alter table public.eventos_brassagem rename constraint brew_batch_events_brew_batch_id_fkey to fk_eventos_brassagem_id_brassagem;
alter table public.eventos_brassagem rename constraint brew_batch_events_created_by_fkey to fk_eventos_brassagem_criado_por;

alter index public.idx_items_type rename to idx_itens_tipo;
alter index public.idx_items_unit_code rename to idx_itens_codigo_unidade;
alter index public.idx_item_lots_item_id rename to idx_lotes_itens_id_item;
alter index public.idx_item_lots_expires_on rename to idx_lotes_itens_validade;
alter index public.idx_item_lots_supplier_id rename to idx_lotes_itens_id_fornecedor;
alter index public.idx_stock_movements_item_id rename to idx_movimentacoes_estoque_id_item;
alter index public.idx_stock_movements_lot_id rename to idx_movimentacoes_estoque_id_lote;
alter index public.idx_stock_movements_occurred_at rename to idx_movimentacoes_estoque_ocorrido_em;
alter index public.idx_stock_movements_created_by rename to idx_movimentacoes_estoque_criado_por;
alter index public.idx_recipe_versions_recipe_id rename to idx_versoes_receitas_id_receita;
alter index public.idx_recipe_inputs_version_id rename to idx_insumos_receita_id_versao_receita;
alter index public.idx_recipe_inputs_item_id rename to idx_insumos_receita_id_item;
alter index public.idx_brew_batches_status rename to idx_brassagens_status;
alter index public.idx_brew_batches_recipe_version_id rename to idx_brassagens_id_versao_receita;
alter index public.idx_brew_batches_created_by rename to idx_brassagens_criado_por;
alter index public.idx_brew_batch_consumptions_batch_id rename to idx_consumos_brassagem_id_brassagem;
alter index public.idx_brew_batch_consumptions_recipe_input_id rename to idx_consumos_brassagem_id_insumo_receita;
alter index public.idx_brew_batch_consumptions_item_id rename to idx_consumos_brassagem_id_item;
alter index public.idx_brew_batch_consumptions_lot_id rename to idx_consumos_brassagem_id_lote;
alter index public.idx_brew_batch_extra_costs_batch_id rename to idx_custos_extras_brassagem_id_brassagem;
alter index public.idx_brew_batch_events_batch_id rename to idx_eventos_brassagem_id_brassagem;
alter index public.idx_brew_batch_events_created_by rename to idx_eventos_brassagem_criado_por;

alter trigger set_app_users_updated_at on public.usuarios_app rename to trg_usuarios_app_atualizado_em;
alter trigger set_suppliers_updated_at on public.fornecedores rename to trg_fornecedores_atualizado_em;
alter trigger set_items_updated_at on public.itens rename to trg_itens_atualizado_em;
alter trigger set_item_lots_updated_at on public.lotes_itens rename to trg_lotes_itens_atualizado_em;
alter trigger set_recipes_updated_at on public.receitas rename to trg_receitas_atualizado_em;
alter trigger set_recipe_versions_updated_at on public.versoes_receitas rename to trg_versoes_receitas_atualizado_em;
alter trigger set_brew_batches_updated_at on public.brassagens rename to trg_brassagens_atualizado_em;
alter trigger set_brew_batch_consumptions_updated_at on public.consumos_brassagem rename to trg_consumos_brassagem_atualizado_em;

alter policy app_users_select_own on public.usuarios_app rename to pl_usuarios_app_ler_proprio;
alter policy app_users_insert_own on public.usuarios_app rename to pl_usuarios_app_inserir_proprio;
alter policy app_users_update_own on public.usuarios_app rename to pl_usuarios_app_atualizar_proprio;
alter policy units_read_authenticated on public.unidades rename to pl_unidades_ler_autenticado;
alter policy suppliers_manage_authenticated on public.fornecedores rename to pl_fornecedores_gerenciar_autenticado;
alter policy items_manage_authenticated on public.itens rename to pl_itens_gerenciar_autenticado;
alter policy item_lots_manage_authenticated on public.lotes_itens rename to pl_lotes_itens_gerenciar_autenticado;
alter policy stock_movements_manage_authenticated on public.movimentacoes_estoque rename to pl_movimentacoes_estoque_gerenciar_autenticado;
alter policy recipes_manage_authenticated on public.receitas rename to pl_receitas_gerenciar_autenticado;
alter policy recipe_versions_manage_authenticated on public.versoes_receitas rename to pl_versoes_receitas_gerenciar_autenticado;
alter policy recipe_inputs_manage_authenticated on public.insumos_receita rename to pl_insumos_receita_gerenciar_autenticado;
alter policy brew_batches_manage_authenticated on public.brassagens rename to pl_brassagens_gerenciar_autenticado;
alter policy brew_batch_consumptions_manage_authenticated on public.consumos_brassagem rename to pl_consumos_brassagem_gerenciar_autenticado;
alter policy brew_batch_extra_costs_manage_authenticated on public.custos_extras_brassagem rename to pl_custos_extras_brassagem_gerenciar_autenticado;
alter policy brew_batch_events_manage_authenticated on public.eventos_brassagem rename to pl_eventos_brassagem_gerenciar_autenticado;
